#!/bin/bash
rm -rf install
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m           • BAIXADOR DE VIDEOS •          \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0m\033[01;37m(1) \033[01;33mBAIXAR VIDEO\033[0m"
echo -e "\033[0m\033[01;37m(2) \033[01;33mBAIXAR MÚSICA\033[0m"
echo -e "\033[0m\033[01;37m(3) \033[01;33mSAIR\033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;32m O QUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m : "
read option
   case $option in
   (1)
   curl -sO https://raw.githubusercontent.com/Savitar44/youtube-dl/main/option-1 && bash option-1
   ;;
   (2)
   curl -sO https://raw.githubusercontent.com/Savitar44/youtube-dl/main/option-2 && bash option-2
   ;;
   (3)
   clear
   exit
   ;;
   (*) echo -e "\033[1;31mOpção inválida! \033[0m"
   sleep 2s
   bash menu

esac
