#!/bin/bash
GREEN='\033[0;32m'
SC='\033[0m'
BLUE='\033[0;34m'
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m          • BAIXAR VÍDEO • \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e
read -p "$(echo -e $GREEN"Digite o link (url): "$SC)" link
sleep 2s
cd /sdcard
clear
echo -e "${GREEN}Procurando Formatos e Resoluções...${SC}"
sleep 2s
youtube-dl -F $link
read -p "$(echo -e $BLUE"Digite a sua escolha: "$SC)" number
sleep 2s
clear
echo -e "${GREEN}Baixando...${SC}"
youtube-dl -f $number $link
sleep 2s
clear
echo -e "${BLUE}Baixado com Sucesso! ${SC}"
sleep 2s
cd
clear
exit

