#!/bin/bash
GREEN='\033[0;32m'
SC='\033[0m'
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m          • BAIXAR VÍDEO • \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e
read -p "$(echo -e $GREEN"Digite o link (url): "$SC)" link
